# Travis CI configuration file
language: python
python:
    - "3.5"
    - "3.6"
install: pip install tox-travis
script: tox
branches:
    except:
        # disable branches beginning with 'draft-
        - /^draft-/
